# Write your MySQL query statement below
SELECT LEFT(TRANS_DATE, 7) MONTH, COUNTRY, COUNT(*) TRANS_COUNT,
SUM(STATE='approved') APPROVED_COUNT, SUM(AMOUNT) TRANS_TOTAL_AMOUNT,
SUM((STATE='approved') * AMOUNT) APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY MONTH, COUNTRY