# Write your MySQL query statement below
SELECT DISTINCT PRODUCT_ID, 10 AS PRICE
FROM PRODUCTS
GROUP BY PRODUCT_ID
HAVING (MIN(CHANGE_DATE) > "2019-08-16")
UNION
SELECT P2.PRODUCT_ID, NEW_PRICE
FROM PRODUCTS P2
WHERE (P2.PRODUCT_ID, P2.CHANGE_DATE) IN (
    SELECT PRODUCT_ID, MAX(CHANGE_DATE) AS RECENT_DATE
    FROM PRODUCTS
    WHERE CHANGE_DATE <= "2019-08-16"
    GROUP BY PRODUCT_ID
)