# Write your MySQL query statement below
SELECT QUERY_NAME, ROUND(AVG(RATING/POSITION), 2) QUALITY, ROUND((SUM(IF(RATING >= 3, 0, 1))/COUNT(*) * 100), 2) POOR_QUERY_PERCENTAGE
FROM QUERIES
GROUP BY QUERY_NAME