# Write your MySQL query statement below
SELECT A.EMPLOYEE_ID, A.NAME, COUNT(B.REPORTS_TO) REPORTS_COUNT, ROUND(AVG(B.AGE)) AVERAGE_AGE
FROM EMPLOYEES A
JOIN EMPLOYEES B
ON A.EMPLOYEE_ID = B.REPORTS_TO
GROUP BY B.REPORTS_TO
ORDER BY A.EMPLOYEE_ID